### ISSUE TITLE
Exception in thread "Thread-8"

### ISSUE THREAD

**Issue by Ironholds** [nexr/RHive#65]
Full error:

> Exception in thread "Thread-8" java.lang.RuntimeException: java.sql.SQLException: >java.lang.ClassNotFoundException
>   at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:337)
>   at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.run(HiveJdbcClient.java:322)
> Caused by: java.sql.SQLException: java.lang.ClassNotFoundException
>   at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:41)
>   at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:330)
>   ... 1 more
> Caused by: java.lang.ClassNotFoundException
>   at RJavaClassLoader.findClass(RJavaClassLoader.java:383)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at java.lang.Class.forName0(Native Method)
>   at java.lang.Class.forName(Class.java:190)
>   at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:38)
>   ... 2 more
> Error: java.lang.IllegalStateException: Not connected to hiveserver

This is with CDH5 and Hive 0.12, and, following:

> Sys.setenv(RHIVE_FS_HOME="/user/ironholds/rhive/")
> library(RHive)
> rhive.init(hiveHome = "usr/lib/hive/", hadoopHome = "/usr/lib/hadoop/", hadoopLib = "/usr/lib/hadoop/lib/", hadoopConf = "/etc/hadoop/conf/")
> rhive.connect(host="analytics1027.eqiad.wmnet",port=10000, hiveServer2=TRUE, defaultFS=NULL,
>                 updateJar=FALSE, user=NULL, password=NULL)

**Comment by jingjingyangg** [comment]
@ssshow16 I did compile the codes with 

`- ant build
- R CMD build RHive
- R CMD INSTALL RHive_2.0-0.10.tar.gz`

But I am having the same error as the OP. Any thoughts? Thanks in advance!
